// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentPlatform.Server.Data;

#nullable disable

namespace RecruitmentPlatform.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218143056_Migration_20251218_01")]
    partial class Migration_20251218_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9254e1ec-eb31-47e0-98d2-079ac1e73047"),
                            CreatedAt = new DateTime(2025, 12, 18, 14, 30, 51, 653, DateTimeKind.Utc).AddTicks(4576),
                            Email = "admin@recruit.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "Admin@123"
                        });
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SelectedAnswerIndex")
                        .HasColumnType("int");

                    b.Property<int>("TimeTakenSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxPossibleScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.InterviewSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PassThresholdPercentage")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("RandomizeQuestions")
                        .HasColumnType("bit");

                    b.Property<int>("TotalQuestionsPerSection")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InterviewSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c26c51b-5e60-4b47-95f9-9601ffaf96ef"),
                            EmailNotificationsEnabled = true,
                            PassThresholdPercentage = 70,
                            QuestionTimeLimitSeconds = 60,
                            RandomizeQuestions = true,
                            TotalQuestionsPerSection = 5,
                            UpdatedAt = new DateTime(2025, 12, 18, 14, 30, 51, 653, DateTimeKind.Utc).AddTicks(4639)
                        });
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2eda02b9-427b-4bd3-aaac-fae5e27c4df0"),
                            CorrectAnswerIndex = 1,
                            Explanation = ".NET provides a common runtime for multiple languages.",
                            Options = "[\"Web development\",\"Multiple language interoperability\",\"Database management\",\"Mobile apps\"]",
                            Points = 10,
                            Section = 0,
                            Text = "What is the primary purpose of the .NET Framework?"
                        },
                        new
                        {
                            Id = new Guid("ab5e4210-6794-4a33-8cb0-a8d810ca005a"),
                            CorrectAnswerIndex = 1,
                            Explanation = "Agile values customer collaboration over contract negotiation.",
                            Options = "[\"Detailed documentation\",\"Customer collaboration\",\"Contract negotiation\",\"Rigid processes\"]",
                            Points = 10,
                            Section = 0,
                            Text = "Which of the following is a key principle of Agile development?"
                        },
                        new
                        {
                            Id = new Guid("c0969af4-bc60-4858-9510-c4a621852d43"),
                            CorrectAnswerIndex = 3,
                            Explanation = "Behavior differs between value types and reference types.",
                            Options = "[\"No difference\",\"== checks reference, Equals checks value\",\"== checks value, Equals checks reference\",\"Depends on the type\"]",
                            Points = 15,
                            Section = 1,
                            Text = "What is the difference between '==' and 'Equals()' in C#?"
                        },
                        new
                        {
                            Id = new Guid("ca383a44-f5a6-44e3-adc0-052db1a17d88"),
                            CorrectAnswerIndex = 2,
                            Explanation = "Where() returns IEnumerable and uses deferred execution.",
                            Options = "[\"ToList()\",\"First()\",\"Where()\",\"Count()\"]",
                            Points = 15,
                            Section = 1,
                            Text = "Which LINQ method is used for deferred execution?"
                        },
                        new
                        {
                            Id = new Guid("afd3c046-06c5-46ff-883d-4f604adc5f3d"),
                            CorrectAnswerIndex = 1,
                            Explanation = "Logs provide diagnostic information for root cause analysis.",
                            Options = "[\"Restart server\",\"Check logs\",\"Scale up instances\",\"Notify all users\"]",
                            Points = 20,
                            Section = 2,
                            Text = "A production API is returning 500 errors sporadically. First step?"
                        },
                        new
                        {
                            Id = new Guid("54b02d99-b484-4257-bab3-ada5eee2373d"),
                            CorrectAnswerIndex = 3,
                            Explanation = "Multiple strategies can be combined for query optimization.",
                            Options = "[\"Use AsNoTracking()\",\"Increase timeout\",\"Add more indexes\",\"All of the above\"]",
                            Points = 20,
                            Section = 2,
                            Text = "How to optimize a slow database query in Entity Framework?"
                        });
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxPossibleScore")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Answer", b =>
                {
                    b.HasOne("RecruitmentPlatform.Server.Models.InterviewSession", "InterviewSession")
                        .WithMany("Answers")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentPlatform.Server.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Application", b =>
                {
                    b.HasOne("RecruitmentPlatform.Server.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.InterviewSession", b =>
                {
                    b.HasOne("RecruitmentPlatform.Server.Models.Application", "Application")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Result", b =>
                {
                    b.HasOne("RecruitmentPlatform.Server.Models.InterviewSession", "InterviewSession")
                        .WithOne("Result")
                        .HasForeignKey("RecruitmentPlatform.Server.Models.Result", "InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.Application", b =>
                {
                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("RecruitmentPlatform.Server.Models.InterviewSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
